name: Build and Publish Multi-arch Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Create new builder
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Build image for Trivy scan (amd64 only)
        id: build-local
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          tags: |
            ghcr.io/grzemotlm/zadanie1_pawcho:${{ github.sha }}
          cache-from: type=registry,ref=grzemo11/zadanie2pawcho:cache
          cache-to:   type=registry,ref=grzemo11/zadanie2pawcho:cache,mode=max

      - name: Scan image for vulnerabilities
        uses: aquasecurity/trivy-action@0.14.0
        with:
          image-ref: ghcr.io/grzemotlm/zadanie1_pawcho:${{ github.sha }}
          severity: CRITICAL,HIGH
          exit-code: 1
          github-pat: ${{ secrets.GITHUB_TOKEN }}

      - name: Push multi-arch image to GHCR
        if: ${{ success() }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/grzemotlm/zadanie1_pawcho:${{ github.sha }}
            ghcr.io/grzemotlm/zadanie1_pawcho:latest
          cache-from: type=registry,ref=grzemo11/zadanie2pawcho:cache
          cache-to:   type=registry,ref=grzemo11/zadanie2pawcho:cache,mode=max
